### ISSUE TITLE
有bug啊

### ISSUE THREAD

**Issue by zhoyou** [hiparker/opsli-boot#13]
系统管理员分配租户管理员时候，新增一个用户，这个用户租户id为0

**Comment by hiparker** [comment]
从那儿个入口进入的 是 租户管理=>分配租户管理员吗

**Comment by zhoyou** [comment]
1.使用系统管理员登录系统
2.新增一个租户
3.选在分配租户管理员
4.新增一个用户
5.正常列表会显示，但没有显示新增的用户数据，导致分配不了管理员

**Comment by zhoyou** [comment]
跟踪了一下代码，新增用户的时候会触发判断是否有system_user_tenant权限。但系统管理员没有这个权限，导致租户id设置为0。查询不到新增租户下的新增的用户数据
